{
    "name": "FEL Guatemala - Swift Solutions",
    "version": "2.8",
    "depends": [
        "base",
        "account",
        "account_debit_note",
        "base_fel",
        "purchase",
        "sale",
        "stock",
        "stock_landed_costs",
        "account_tax_python",
    ],
    "assets": {"web.assets_qweb": ["fel/static/src/css/reporte_factura.css"]},
    "data": [
        "security/ir.model.access.csv",
        "report/report_invoice_document_swift.xml",
        "views/frases_fel_vista_main.xml",
        "views/res_company_company_view.xml",
        "views/account_tax_inherit_view.xml",
        "views/account_move_special_invoice_menu.xml",
        "views/account_move_special_invoice_view.xml",
        "views/account_move_inherit_view.xml",
        "views/account_journal_inherit_view.xml",
        "views/wizard_anular_facturas_view.xml",
        "views/account_move_fact_type.xml",
        "views/account_move_nota_debito_view.xml",
        "views/account_move_nota_debito_menu_view.xml",
        "views/account_move_exportacion_view.xml",
        "views/res_partner_information_view.xml",
        "views/res_partner_exportacion_campos.xml",
        "views/res_config_settings_views.xml",
        "views/account_move_supplier_invoice.xml",
        "views/account_move_posiciones_fiscales.xml",
        "views/account_move_customer_invoice.xml",
        "views/account_move_vendor_invoice.xml",
        "views/account_payment_form_view.xml",
        "views/res_partner_list_view.xml",
        "views/account_move_invoice_search_inherit.xml",
        "views/account_view_out_invoice_tree_inherit.xml",
        "views/account_view_in_invoice_bill_tree_inherit.xml",
    ],
    "installable": True,
    "application": False,
}
